# Variables
@host = localhost:3000

# Home entry point
GET http://{{host}}/ HTTP/1.1


### Users

# Query all users
GET http://{{host}}/users HTTP/1.1

# Create new user
POST http://{{host}}/users HTTP/1.1
Content-Type: application/json

{
    "email": "beltrano@mailinator.out",
    "name": "BeltranoSilva",
    "password": "1234qwerA"
}